"""conversation persistence

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-29 21:06:03.779565
"""

import sqlalchemy as sa
from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("title_source", sa.String(length=8), nullable=False, server_default="auto")
        )
        batch_op.add_column(sa.Column("summary", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("summary_upto_message_id", sa.Integer(), nullable=True))

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("kind", sa.String(length=16), nullable=False, server_default="message")
        )
        batch_op.add_column(
            sa.Column("status", sa.String(length=16), nullable=False, server_default="complete")
        )
        batch_op.add_column(sa.Column("tokens_in", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("tokens_out", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("tool_calls", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("tool_call_id", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("tool_name", sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_column("tool_name")
        batch_op.drop_column("tool_call_id")
        batch_op.drop_column("tool_calls")
        batch_op.drop_column("tokens_out")
        batch_op.drop_column("tokens_in")
        batch_op.drop_column("status")
        batch_op.drop_column("kind")

    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_column("summary_upto_message_id")
        batch_op.drop_column("summary")
        batch_op.drop_column("title_source")

    # ### end Alembic commands ###
