"""memory metadata

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-29 21:16:24.763780
"""

import sqlalchemy as sa
from alembic import op

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("memories", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("importance", sa.Integer(), nullable=False, server_default="3")
        )
        batch_op.add_column(
            sa.Column("use_count", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(sa.Column("content_hash", sa.String(length=64), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_memories_content_hash"), ["content_hash"], unique=False
        )

    # ### end Alembic commands ###

    # Backfill the duplicate-detection hash for memories created before this migration
    # (for example ones imported from the prototype's JSON file). The hashing rule is
    # copied here so the migration does not depend on application code that may change.
    import hashlib

    connection = op.get_bind()
    rows = connection.execute(sa.text("SELECT id, content FROM memories")).fetchall()
    for row_id, content in rows:
        digest = hashlib.sha256(" ".join((content or "").lower().split()).encode()).hexdigest()
        connection.execute(
            sa.text("UPDATE memories SET content_hash = :h WHERE id = :i"),
            {"h": digest, "i": row_id},
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("memories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memories_content_hash"))
        batch_op.drop_column("content_hash")
        batch_op.drop_column("use_count")
        batch_op.drop_column("importance")

    # ### end Alembic commands ###
