"""tool runs

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-29 21:24:39.563495
"""

import sqlalchemy as sa
from alembic import op

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tool_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=True),
        sa.Column("agent_run_id", sa.Integer(), nullable=True),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("risk", sa.String(length=16), nullable=False),
        sa.Column("requires_confirmation", sa.Boolean(), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("arguments", sa.JSON(), nullable=True),
        sa.Column("raw_arguments", sa.Text(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tool_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tool_runs_agent_run_id"), ["agent_run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tool_runs_conversation_id"), ["conversation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tool_runs_tool_name"), ["tool_name"], unique=False)
        batch_op.create_index("ix_tool_runs_user_created", ["user_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_tool_runs_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tool_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tool_runs_user_id"))
        batch_op.drop_index("ix_tool_runs_user_created")
        batch_op.drop_index(batch_op.f("ix_tool_runs_tool_name"))
        batch_op.drop_index(batch_op.f("ix_tool_runs_conversation_id"))
        batch_op.drop_index(batch_op.f("ix_tool_runs_agent_run_id"))

    op.drop_table("tool_runs")
    # ### end Alembic commands ###
