"""error records

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-30 09:38:10.013684
"""

import sqlalchemy as sa
from alembic import op

revision = "0009"
down_revision = "0008"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "error_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("details", sa.Text(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("resolution", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("error_records", schema=None) as batch_op:
        batch_op.create_index("ix_error_records_created", ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_error_records_kind"), ["kind"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("error_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_error_records_kind"))
        batch_op.drop_index("ix_error_records_created")

    op.drop_table("error_records")
    # ### end Alembic commands ###
